%YAML 1.2
---
# Extracts a concept map from a text.
transformers:
    - pos_extract
    - wordnet
    - numerals
    - attach_adjectives
    - negation
    - genitive
    - prep_rise
    - unique
    - verb_collapse
    - lenient
transformer_args:
    sempos:
        noun: n
        adjective: j
    retain_attachments: False
operations:
    - op: filter_edges
      remove:
        - isa
        - of
      rename:
        be: is
      frequency:
        max: 15
        min: 0
    - op: spot_domain
linearizers:
    - prolog
