%YAML 1.2
---
# Extracts a concept map from a text.
transformers:
    - pos_extract
    - attach
    - negation
    - genitive
    - prep_rise
    - unique
    - verb_collapse
    - lenient
transformer_args:
    sempos:
        noun: n
        adjective: j
operations:
    - op: filter_edges
      remove:
        - isa
        - of
    - op: spot_domain
linearizers:
    - prolog
