%YAML 1.2
---
# Extracts a concept map from a text.
#
# TODO: prep rising
#       unique n's and j's
#       improve attach
transformers:
    - pos_extract
    - attach
    - unique
    - prep_rise
    - verb_collapse
transformer_args:
    sempos:
        noun: n
        adjective: j
linearizers:
    - triplets
