%YAML 1.2
---
# Extracts a concept map from a text.
#
# TODO: improve attach
transformers:
    - pos_extract
    - attach
    - negation
    - unique
    - prep_rise
    - verb_collapse
    - lenient
transformer_args:
    sempos:
        noun: n
        adjective: j
linearizers:
    - triplets
