transformers:
    - pos_extract
    - unique
    - keep_deps
    - edge_reverse
transformer_args:
    sempos:
        noun: n
        verb: v
        adjective: j
        adverb: r
        preposition: p
    unique_sempos: [ n, j, r ]
    reversed_edges:
        - AGENT
