%YAML 1.2
---
# Extracts a concept map from a text.
transformers:
    - pos_extract
    - pronouns
    - nouns
    - thematic
    - phrasal
    - genitive
    - prepositions
    - adjectives
    - adverbs
    - negation
    - interrogative
    - copula
    - lenient
linearizers:
    - node_edges
