%YAML 1.2
---
# Extracts a concept map from a text.
transformers:
    - pos_extract
    - nouns
    - thematic
    - phrasal
    - genitive
    - prepositions
    #- numerals
    - adjectives
    - adverbs
    - negation
    - wordnet
    - attr_class
transformer_args: {}
linearizers:
    - triplets
